//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "7b00b7170c227b0b")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// VintageAdres
		///</summary>
		[ImplementPropertyType("vintageAdres")]
		public string VintageAdres
		{
			get { return this.GetPropertyValue<string>("vintageAdres"); }
		}

		///<summary>
		/// VintageEmail
		///</summary>
		[ImplementPropertyType("vintageEmail")]
		public string VintageEmail
		{
			get { return this.GetPropertyValue<string>("vintageEmail"); }
		}

		///<summary>
		/// VintageGSM
		///</summary>
		[ImplementPropertyType("vintageGSM")]
		public string VintageGsm
		{
			get { return this.GetPropertyValue<string>("vintageGSM"); }
		}
	}

	/// <summary>Info</summary>
	[PublishedContentModel("info")]
	public partial class Info : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "info";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Info(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Info, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// InfoPart1Text
		///</summary>
		[ImplementPropertyType("infoPart1Text")]
		public string InfoPart1Text
		{
			get { return this.GetPropertyValue<string>("infoPart1Text"); }
		}

		///<summary>
		/// InfoPart1Title
		///</summary>
		[ImplementPropertyType("infoPart1Title")]
		public string InfoPart1Title
		{
			get { return this.GetPropertyValue<string>("infoPart1Title"); }
		}

		///<summary>
		/// InfoPart2Text
		///</summary>
		[ImplementPropertyType("infoPart2Text")]
		public string InfoPart2Text
		{
			get { return this.GetPropertyValue<string>("infoPart2Text"); }
		}

		///<summary>
		/// InfoPart2Title
		///</summary>
		[ImplementPropertyType("infoPart2Title")]
		public string InfoPart2Title
		{
			get { return this.GetPropertyValue<string>("infoPart2Title"); }
		}

		///<summary>
		/// InfoPart3Text
		///</summary>
		[ImplementPropertyType("infoPart3Text")]
		public string InfoPart3Text
		{
			get { return this.GetPropertyValue<string>("infoPart3Text"); }
		}

		///<summary>
		/// InfoPart3Title
		///</summary>
		[ImplementPropertyType("infoPart3Title")]
		public string InfoPart3Title
		{
			get { return this.GetPropertyValue<string>("infoPart3Title"); }
		}
	}

	/// <summary>Parts</summary>
	[PublishedContentModel("parts")]
	public partial class Parts : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "parts";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Parts(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Parts, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Basepage</summary>
	[PublishedContentModel("basepage")]
	public partial class Basepage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "basepage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Basepage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Basepage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// HomeBannerImage: Afbeelding voor homepage
		///</summary>
		[ImplementPropertyType("homeBannerImage")]
		public IPublishedContent HomeBannerImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("homeBannerImage"); }
		}

		///<summary>
		/// HomeBannerText: Tekst voor op de banner bij de homepage
		///</summary>
		[ImplementPropertyType("homeBannerText")]
		public string HomeBannerText
		{
			get { return this.GetPropertyValue<string>("homeBannerText"); }
		}

		///<summary>
		/// Title: Title for the webpage
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Part</summary>
	[PublishedContentModel("part")]
	public partial class Part : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "part";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Part(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Part, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// MorePartPictures: Laad hier extra afbeeldingen op van het onderdeel
		///</summary>
		[ImplementPropertyType("morePartPictures")]
		public IEnumerable<IPublishedContent> MorePartPictures
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("morePartPictures"); }
		}

		///<summary>
		/// PartDescription: Omschrijving van het onderdeel
		///</summary>
		[ImplementPropertyType("partDescription")]
		public string PartDescription
		{
			get { return this.GetPropertyValue<string>("partDescription"); }
		}

		///<summary>
		/// PartName: Geef hier de naam van het onderdeel
		///</summary>
		[ImplementPropertyType("partName")]
		public string PartName
		{
			get { return this.GetPropertyValue<string>("partName"); }
		}

		///<summary>
		/// PartPicture: De eerste afbeelding van het onderdeel
		///</summary>
		[ImplementPropertyType("partPicture")]
		public IPublishedContent PartPicture
		{
			get { return this.GetPropertyValue<IPublishedContent>("partPicture"); }
		}

		///<summary>
		/// PartPrice: De prijs van het onderdeel
		///</summary>
		[ImplementPropertyType("partPrice")]
		public string PartPrice
		{
			get { return this.GetPropertyValue<string>("partPrice"); }
		}
	}

	/// <summary>Slider</summary>
	[PublishedContentModel("slider")]
	public partial class Slider : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slider";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Slider(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Slider, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meeting media
		///</summary>
		[ImplementPropertyType("meetingMedia")]
		public IEnumerable<IPublishedContent> MeetingMedia
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("meetingMedia"); }
		}
	}

	/// <summary>notfound</summary>
	[PublishedContentModel("notfound")]
	public partial class Notfound : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "notfound";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Notfound(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Notfound, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Store</summary>
	[PublishedContentModel("store")]
	public partial class Store : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "store";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Store(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Store, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// StoreName: Type the name of the items that will be sold in this store
		///</summary>
		[ImplementPropertyType("storeName")]
		public string StoreName
		{
			get { return this.GetPropertyValue<string>("storeName"); }
		}
	}

	/// <summary>StoreItem</summary>
	[PublishedContentModel("storeItem")]
	public partial class StoreItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "storeItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StoreItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StoreItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// AndereFotos
		///</summary>
		[ImplementPropertyType("andereFotos")]
		public IEnumerable<IPublishedContent> AndereFotos
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("andereFotos"); }
		}

		///<summary>
		/// Bouwjaar
		///</summary>
		[ImplementPropertyType("bouwjaar")]
		public string Bouwjaar
		{
			get { return this.GetPropertyValue<string>("bouwjaar"); }
		}

		///<summary>
		/// ExtraTekst
		///</summary>
		[ImplementPropertyType("extraTekst")]
		public string ExtraTekst
		{
			get { return this.GetPropertyValue<string>("extraTekst"); }
		}

		///<summary>
		/// IsVerkocht: Duid aan of dit item al verkocht is of niet
		///</summary>
		[ImplementPropertyType("isVerkocht")]
		public bool IsVerkocht
		{
			get { return this.GetPropertyValue<bool>("isVerkocht"); }
		}

		///<summary>
		/// Merk
		///</summary>
		[ImplementPropertyType("merk")]
		public string Merk
		{
			get { return this.GetPropertyValue<string>("merk"); }
		}

		///<summary>
		/// Model
		///</summary>
		[ImplementPropertyType("model")]
		public string Model
		{
			get { return this.GetPropertyValue<string>("model"); }
		}

		///<summary>
		/// Prijs
		///</summary>
		[ImplementPropertyType("prijs")]
		public string Prijs
		{
			get { return this.GetPropertyValue<string>("prijs"); }
		}

		///<summary>
		/// PrimaireFoto: De eerste foto die op het overzicht getoond wordt
		///</summary>
		[ImplementPropertyType("primaireFoto")]
		public IPublishedContent PrimaireFoto
		{
			get { return this.GetPropertyValue<IPublishedContent>("primaireFoto"); }
		}

		///<summary>
		/// Video: provide a youtube url
		///</summary>
		[ImplementPropertyType("video")]
		public string Video
		{
			get { return this.GetPropertyValue<string>("video"); }
		}
	}

	/// <summary>StoreForSale</summary>
	[PublishedContentModel("storeForSale")]
	public partial class StoreForSale : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "storeForSale";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StoreForSale(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StoreForSale, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// PaginaEmpty: Indien deze pagina toch gepublished is maar geen items te koop bevat
		///</summary>
		[ImplementPropertyType("paginaEmpty")]
		public string PaginaEmpty
		{
			get { return this.GetPropertyValue<string>("paginaEmpty"); }
		}

		///<summary>
		/// PaginaTitel: De titel om op de verkoop pagia te hebben
		///</summary>
		[ImplementPropertyType("paginaTitel")]
		public string PaginaTitel
		{
			get { return this.GetPropertyValue<string>("paginaTitel"); }
		}

		///<summary>
		/// PaginaWelkom: Korte tekst en uitleg
		///</summary>
		[ImplementPropertyType("paginaWelkom")]
		public string PaginaWelkom
		{
			get { return this.GetPropertyValue<string>("paginaWelkom"); }
		}
	}

	/// <summary>StoreSold</summary>
	[PublishedContentModel("storeSold")]
	public partial class StoreSold : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "storeSold";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StoreSold(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StoreSold, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// PaginaEmpty: Indien deze pagina toch gepublished maar er geen verkochte items zijn
		///</summary>
		[ImplementPropertyType("paginaEmpty")]
		public string PaginaEmpty
		{
			get { return this.GetPropertyValue<string>("paginaEmpty"); }
		}

		///<summary>
		/// PaginaTitel: Titel van deze pagina
		///</summary>
		[ImplementPropertyType("paginaTitel")]
		public string PaginaTitel
		{
			get { return this.GetPropertyValue<string>("paginaTitel"); }
		}

		///<summary>
		/// PaginaWelkom: Klein woordje uitleg net onder de titel
		///</summary>
		[ImplementPropertyType("paginaWelkom")]
		public string PaginaWelkom
		{
			get { return this.GetPropertyValue<string>("paginaWelkom"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
