//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Part</summary>
	[PublishedContentModel("part")]
	public partial class Part : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "part";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Part(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Part, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// MorePartPictures: Laad hier extra afbeeldingen op van het onderdeel
		///</summary>
		[ImplementPropertyType("morePartPictures")]
		public IEnumerable<IPublishedContent> MorePartPictures
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("morePartPictures"); }
		}

		///<summary>
		/// PartDescription: Omschrijving van het onderdeel
		///</summary>
		[ImplementPropertyType("partDescription")]
		public string PartDescription
		{
			get { return this.GetPropertyValue<string>("partDescription"); }
		}

		///<summary>
		/// PartName: Geef hier de naam van het onderdeel
		///</summary>
		[ImplementPropertyType("partName")]
		public string PartName
		{
			get { return this.GetPropertyValue<string>("partName"); }
		}

		///<summary>
		/// PartPicture: De eerste afbeelding van het onderdeel
		///</summary>
		[ImplementPropertyType("partPicture")]
		public IPublishedContent PartPicture
		{
			get { return this.GetPropertyValue<IPublishedContent>("partPicture"); }
		}

		///<summary>
		/// PartPrice: De prijs van het onderdeel
		///</summary>
		[ImplementPropertyType("partPrice")]
		public string PartPrice
		{
			get { return this.GetPropertyValue<string>("partPrice"); }
		}
	}
}
