//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>StoreSold</summary>
	[PublishedContentModel("storeSold")]
	public partial class StoreSold : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "storeSold";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StoreSold(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StoreSold, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// PaginaEmpty: Indien deze pagina toch gepublished maar er geen verkochte items zijn
		///</summary>
		[ImplementPropertyType("paginaEmpty")]
		public string PaginaEmpty
		{
			get { return this.GetPropertyValue<string>("paginaEmpty"); }
		}

		///<summary>
		/// PaginaTitel: Titel van deze pagina
		///</summary>
		[ImplementPropertyType("paginaTitel")]
		public string PaginaTitel
		{
			get { return this.GetPropertyValue<string>("paginaTitel"); }
		}

		///<summary>
		/// PaginaWelkom: Klein woordje uitleg net onder de titel
		///</summary>
		[ImplementPropertyType("paginaWelkom")]
		public string PaginaWelkom
		{
			get { return this.GetPropertyValue<string>("paginaWelkom"); }
		}
	}
}
