//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>StoreItem</summary>
	[PublishedContentModel("storeItem")]
	public partial class StoreItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "storeItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StoreItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StoreItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// AndereFotos
		///</summary>
		[ImplementPropertyType("andereFotos")]
		public IEnumerable<IPublishedContent> AndereFotos
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("andereFotos"); }
		}

		///<summary>
		/// Bouwjaar
		///</summary>
		[ImplementPropertyType("bouwjaar")]
		public string Bouwjaar
		{
			get { return this.GetPropertyValue<string>("bouwjaar"); }
		}

		///<summary>
		/// ExtraTekst
		///</summary>
		[ImplementPropertyType("extraTekst")]
		public string ExtraTekst
		{
			get { return this.GetPropertyValue<string>("extraTekst"); }
		}

		///<summary>
		/// IsVerkocht: Duid aan of dit item al verkocht is of niet
		///</summary>
		[ImplementPropertyType("isVerkocht")]
		public bool IsVerkocht
		{
			get { return this.GetPropertyValue<bool>("isVerkocht"); }
		}

		///<summary>
		/// Merk
		///</summary>
		[ImplementPropertyType("merk")]
		public string Merk
		{
			get { return this.GetPropertyValue<string>("merk"); }
		}

		///<summary>
		/// Model
		///</summary>
		[ImplementPropertyType("model")]
		public string Model
		{
			get { return this.GetPropertyValue<string>("model"); }
		}

		///<summary>
		/// Prijs
		///</summary>
		[ImplementPropertyType("prijs")]
		public string Prijs
		{
			get { return this.GetPropertyValue<string>("prijs"); }
		}

		///<summary>
		/// PrimaireFoto: De eerste foto die op het overzicht getoond wordt
		///</summary>
		[ImplementPropertyType("primaireFoto")]
		public IPublishedContent PrimaireFoto
		{
			get { return this.GetPropertyValue<IPublishedContent>("primaireFoto"); }
		}

		///<summary>
		/// Video: provide a youtube url
		///</summary>
		[ImplementPropertyType("video")]
		public string Video
		{
			get { return this.GetPropertyValue<string>("video"); }
		}
	}
}
