//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>StoreForSale</summary>
	[PublishedContentModel("storeForSale")]
	public partial class StoreForSale : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "storeForSale";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StoreForSale(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StoreForSale, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// PaginaEmpty: Indien deze pagina toch gepublished is maar geen items te koop bevat
		///</summary>
		[ImplementPropertyType("paginaEmpty")]
		public string PaginaEmpty
		{
			get { return this.GetPropertyValue<string>("paginaEmpty"); }
		}

		///<summary>
		/// PaginaTitel: De titel om op de verkoop pagia te hebben
		///</summary>
		[ImplementPropertyType("paginaTitel")]
		public string PaginaTitel
		{
			get { return this.GetPropertyValue<string>("paginaTitel"); }
		}

		///<summary>
		/// PaginaWelkom: Korte tekst en uitleg
		///</summary>
		[ImplementPropertyType("paginaWelkom")]
		public string PaginaWelkom
		{
			get { return this.GetPropertyValue<string>("paginaWelkom"); }
		}
	}
}
